name: Re-request PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  re-request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.REVIEW_TOKEN }}
          reviewers: review-deriv
          re-request: true
