name: Re-request PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  re-request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          reviewers: '["review-deriv"]'
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEW_TOKEN }}
      
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          reviewers: '["review-deriv"]'
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEW_TOKEN }}
