name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Handle PR and Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWER: review-deriv
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Requesting review for PR #${{ github.event.pull_request.number }}"
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
              -d "{\"reviewers\":[\"$REVIEWER\"]}"
          else
            current_branch="${{ github.ref_name }}"
            
            # Get default branch without using GraphQL
            default_branch=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}" \
              | jq -r .default_branch)
            
            echo "Current branch: $current_branch"
            echo "Default branch: $default_branch"
            
            # Check for existing PR using REST API
            existing_pr=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:$current_branch&state=open" \
              | jq -r '.[0].number')
            
            if [[ "$existing_pr" == "null" ]]; then
              echo "Creating new PR..."
              # Create PR using REST API
              pr_response=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/pulls" \
                -d "{
                  \"title\":\"Review requested for $current_branch\",
                  \"body\":\"Automated pull request for review\",
                  \"head\":\"$current_branch\",
                  \"base\":\"$default_branch\"
                }")
              
              pr_number=$(echo "$pr_response" | jq -r .number)
              echo "Created PR #$pr_number"
              
              # Request review for the new PR
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/requested_reviewers" \
                -d "{\"reviewers\":[\"$REVIEWER\"]}"
            else
              echo "PR already exists: #$existing_pr"
              # Request review for existing PR
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/$existing_pr/requested_reviewers" \
                -d "{\"reviewers\":[\"$REVIEWER\"]}"
            fi
          fi
