name: Request PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          reviewers: "review-deriv"
          token: ${{ secrets.REVIEW_TOKEN }}
