name: Request PR Review

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_target:
    types: [opened, synchronize]

jobs:
  request-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Request Review
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['review-deriv']
            });
