name: Re-request PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dismiss-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss and Re-request Review
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.REVIEW_TOKEN }}
          script: |
            // First dismiss any existing reviews
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            for (const review of reviews.data) {
              if (review.user.login === 'review-deriv') {
                await github.rest.pulls.dismissReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  review_id: review.id,
                  message: 'Dismissed due to new changes'
                });
              }
            }
            
            // Then request a new review
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['review-deriv']
            });
