name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main
      - master

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Request Review
        uses: rowi1de/auto-assign-review@v1.2.5
        with:
          repo-token: ${{ secrets.REVIEW_TOKEN }}
          reviewers: review-deriv
          max-num-of-reviewers: 1

      # Fallback for push events to create PR if needed
      - name: Create Pull Request
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.REVIEW_TOKEN }}
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          default_branch=$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)
          
          # Check for existing PR
          existing_pr=$(gh pr list --head "$current_branch" --state open --json number --jq '.[0].number')
          
          if [ -z "$existing_pr" ]; then
            echo "Creating new PR..."
            gh pr create --title "Review requested for $current_branch" \
                        --body "Automated pull request for review" \
                        --base "$default_branch" \
                        --head "$current_branch"
          else
            echo "PR already exists: #$existing_pr"
          fi
